image: Visual Studio 2019

clone_folder: C:\vim-mesonist

clone_depth: 1

init:
  - git config --global core.autocrlf input
  - set PYTHON_PATH=C:\Python38
  - set PYTHON_SCRIPTS=C:\Python38\Scripts

install:
  - set PATH=%PYTHON_PATH%;%PYTHON_SCRIPTS%;%PATH%
  - python -V
  - python -m pip install meson
  - meson --version
  - cinst vim
  - vim --version
  - cd C:\vim-mesonist
  - git clone --depth 1 https://github.com/junegunn/vader.vim

build_script:
  - ls
  - set VADER_OUTPUT_FILE=C:\vim-mesonist\vader.log
  - vim --no-fork -Nu ./test/.vimrc -c '+Vader! test/meson-build-file-error.vader' --not-a-term
